arrow-parens = "always"
bracket-same-line = false
embedded-language-formatting = "auto"
end-of-line = "lf"
html-whitespace-sensitivity = "css"
jsx-single-quote = false
print-width = 80
prose-wrap = "preserve"
quote-props = "as-needed"
semi = true
single-attribute-per-line = false
single-quote = false
tab-width = 2
trailing-comma = "es5"
use-tabs = false
vue-indent-script-and-style = false
